"""
backend/services/simulation_service.py
========================================
Phase 12: Simulated Real-Time Monitoring Service

WHAT THIS IS
------------
A step-based simulation engine that reads rows from the AI4I 2020 synthetic
dataset sequentially and runs the existing ML pipeline on each row. It
demonstrates how INDUSTRIA-X would behave when machine data arrives over time.

WHAT THIS IS NOT
----------------
This is NOT a real-time industrial sensor system. It does NOT connect to
any physical machine, sensor network, or industrial control system. All data
originates from the AI4I 2020 synthetic dataset (Matzka, 2021), released
under CC BY 4.0.

ARCHITECTURE
------------
- Stateful singleton per process (in-memory, not distributed).
- Step-based: the frontend requests one step at a time (or batches).
- No background threads / background tasks by default — keeps behaviour
  predictable and avoids concurrency surprises in a demonstration environment.
- Dataset is loaded lazily at first start; a FileNotFoundError is surfaced
  cleanly if the CSV is absent.
- No data is persisted to PostgreSQL — simulation history lives in memory.

ALERT LOGIC
-----------
Alerts are deterministic and generated whenever:
 - risk_level changes to WARNING or CRITICAL (transition alert)
 - is_anomaly becomes True
 - failure_probability crosses the model's classification threshold

All alert text is informational ("Simulation alert: …").
No alert says "Machine will fail."

SYNTHETIC DATA NOTICE
---------------------
All sensor readings, failure events, and anomaly events shown during
simulation originate from a synthetic dataset generated by an algorithm.
They do not represent measurements from real factory equipment.
"""

from __future__ import annotations

import threading
from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from pathlib import Path
from typing import Any

# ── Simulation state enumeration ─────────────────────────────────────────────


class SimulationState(str, Enum):
    IDLE = "idle"
    RUNNING = "running"
    PAUSED = "paused"
    FINISHED = "finished"


# ── Speed presets (used only as labels; step rate is driven by the client) ────

SPEED_PRESETS: dict[str, str] = {
    "slow":   "slow",
    "normal": "normal",
    "fast":   "fast",
}

# ── Configurable limits ───────────────────────────────────────────────────────

#: Maximum number of alert records kept in memory.
MAX_ALERTS = 50

#: Maximum number of event records kept in memory.
MAX_HISTORY = 100

#: Simulated machine identifier shown in the UI (clearly synthetic).
SIMULATED_MACHINE_ID = "SIM-AI4I-001"


# ── Event dataclass ───────────────────────────────────────────────────────────


@dataclass
class SimulationEvent:
    """One simulation step result."""

    simulation_step: int
    simulated_time_label: str          # e.g. "Step 142" — not a real wall clock
    machine_identifier: str
    sensor_values: dict[str, Any]      # raw sensor readings from the dataset row
    failure_probability: float
    anomaly_score: float
    risk_score: float
    risk_level: str
    is_anomaly: bool
    predicted_failure: int
    failure_threshold: float
    model_version: str
    real_wall_time: str                # actual wall-clock time of this step (UTC ISO)

    def to_dict(self) -> dict[str, Any]:
        return {
            "simulation_step": self.simulation_step,
            "simulated_time_label": self.simulated_time_label,
            "machine_identifier": self.machine_identifier,
            "sensor_values": self.sensor_values,
            "failure_probability": self.failure_probability,
            "anomaly_score": self.anomaly_score,
            "risk_score": self.risk_score,
            "risk_level": self.risk_level,
            "is_anomaly": self.is_anomaly,
            "predicted_failure": self.predicted_failure,
            "failure_threshold": self.failure_threshold,
            "model_version": self.model_version,
            "real_wall_time": self.real_wall_time,
        }


@dataclass
class SimulationAlert:
    """A deterministic alert generated during simulation."""

    step: int
    alert_type: str       # "RISK_WARNING", "RISK_CRITICAL", "ANOMALY", "FAILURE_THRESHOLD"
    message: str
    risk_level: str
    real_wall_time: str

    def to_dict(self) -> dict[str, Any]:
        return {
            "step": self.step,
            "alert_type": self.alert_type,
            "message": self.message,
            "risk_level": self.risk_level,
            "real_wall_time": self.real_wall_time,
        }


# ── Core simulation engine ────────────────────────────────────────────────────


class SimulationEngine:
    """
    In-memory, step-based simulation engine.

    Thread-safe for single-writer / single-reader use (one active step at a time).

    All simulation state is ephemeral — restart the process or call reset()
    to clear it.
    """

    def __init__(self) -> None:
        self._lock = threading.Lock()
        self._state: SimulationState = SimulationState.IDLE
        self._rows: list[dict[str, Any]] = []       # dataset rows as dicts
        self._total_rows: int = 0
        self._current_step: int = 0                  # 0-based index into _rows
        self._current_event: SimulationEvent | None = None
        self._previous_risk_level: str | None = None
        self._previous_is_anomaly: bool | None = None
        self._alerts: list[SimulationAlert] = []
        self._history: list[SimulationEvent] = []
        self._speed: str = "normal"
        self._dataset_error: str | None = None

    # ── Public properties ─────────────────────────────────────────────────────

    @property
    def state(self) -> SimulationState:
        return self._state

    @property
    def current_step(self) -> int:
        return self._current_step

    @property
    def total_steps(self) -> int:
        return self._total_rows

    @property
    def current_event(self) -> SimulationEvent | None:
        return self._current_event

    @property
    def alerts(self) -> list[SimulationAlert]:
        return list(self._alerts)

    @property
    def history(self) -> list[SimulationEvent]:
        return list(self._history)

    @property
    def speed(self) -> str:
        return self._speed

    # ── Lifecycle commands ────────────────────────────────────────────────────

    def start(self, speed: str = "normal") -> None:
        """Load dataset (if not loaded) and set state to RUNNING.

        Raises
        ------
        FileNotFoundError
            If the AI4I dataset CSV cannot be found.
        ValueError
            If the dataset is malformed.
        """
        with self._lock:
            if speed not in SPEED_PRESETS:
                speed = "normal"
            self._speed = speed

            # Load dataset if not already loaded
            if not self._rows:
                self._load_dataset()

            if self._state == SimulationState.FINISHED:
                # Auto-wrap: reset position but keep dataset loaded
                self._current_step = 0
                self._current_event = None
                self._previous_risk_level = None
                self._previous_is_anomaly = None

            self._state = SimulationState.RUNNING

    def pause(self) -> None:
        """Pause the simulation (state → PAUSED, does not reset position)."""
        with self._lock:
            if self._state == SimulationState.RUNNING:
                self._state = SimulationState.PAUSED

    def resume(self) -> None:
        """Resume a paused simulation."""
        with self._lock:
            if self._state == SimulationState.PAUSED:
                self._state = SimulationState.RUNNING

    def reset(self) -> None:
        """Return to initial state (keeps dataset in memory for speed)."""
        with self._lock:
            self._state = SimulationState.IDLE
            self._current_step = 0
            self._current_event = None
            self._previous_risk_level = None
            self._previous_is_anomaly = None
            self._alerts = []
            self._history = []
            # Keep _rows and _total_rows loaded for fast restart

    def step(self) -> SimulationEvent:
        """Advance by one dataset row and evaluate it.

        Returns
        -------
        SimulationEvent
            The result of processing the current row.

        Raises
        ------
        RuntimeError
            If the simulation is not RUNNING or PAUSED (allow stepping while
            paused for manual stepping mode).
        IndexError
            If simulation has reached the end of the dataset.
        FileNotFoundError
            If ML artifacts are missing.
        """
        with self._lock:
            if self._state not in (SimulationState.RUNNING, SimulationState.PAUSED):
                if self._state == SimulationState.IDLE:
                    # Auto-start if dataset is ready
                    if not self._rows:
                        self._load_dataset()
                    self._state = SimulationState.RUNNING
                elif self._state == SimulationState.FINISHED:
                    raise IndexError("Simulation has reached the end of the dataset. Call reset() to restart.")

            if not self._rows:
                self._load_dataset()

            if self._current_step >= self._total_rows:
                self._state = SimulationState.FINISHED
                raise IndexError("Simulation has reached the end of the dataset. Call reset() to restart.")

            row = self._rows[self._current_step]
            step_number = self._current_step + 1  # 1-based for display

            event = self._evaluate_row(row, step_number)

            # Generate alerts (deterministic)
            self._generate_alerts(event)

            # Track history
            self._history.append(event)
            if len(self._history) > MAX_HISTORY:
                self._history = self._history[-MAX_HISTORY:]

            self._current_event = event
            self._previous_risk_level = event.risk_level
            self._previous_is_anomaly = event.is_anomaly
            self._current_step += 1

            if self._current_step >= self._total_rows:
                self._state = SimulationState.FINISHED

            return event

    def status(self) -> dict[str, Any]:
        """Return a snapshot of the current simulation status."""
        with self._lock:
            return {
                "state": self._state.value,
                "speed": self._speed,
                "current_step": self._current_step,
                "total_steps": self._total_rows,
                "current_event": self._current_event.to_dict() if self._current_event else None,
                "recent_alerts": [a.to_dict() for a in self._alerts[-10:]],
                "dataset_error": self._dataset_error,
            }

    # ── Internal helpers ──────────────────────────────────────────────────────

    def _load_dataset(self) -> None:
        """Load and cache dataset rows from disk.

        Raises FileNotFoundError / ValueError on failure.
        Must be called under self._lock.
        """
        try:
            from ml.data.loader import load_raw  # noqa: PLC0415
        except ImportError as exc:
            self._dataset_error = "ML data module unavailable."
            raise RuntimeError("ML data module unavailable.") from exc

        try:
            df = load_raw()
        except FileNotFoundError as exc:
            self._dataset_error = (
                "Simulation dataset unavailable. "
                "Place ai4i2020.csv in data/raw/ to enable simulation."
            )
            raise

        # Validate required columns are present
        required = [
            "Type",
            "Air temperature [K]",
            "Process temperature [K]",
            "Rotational speed [rpm]",
            "Torque [Nm]",
            "Tool wear [min]",
            "Product ID",
        ]
        missing = [c for c in required if c not in df.columns]
        if missing:
            self._dataset_error = f"Dataset missing columns: {missing}"
            raise ValueError(f"Dataset missing required columns: {missing}")

        # Store as list of dicts for fast row access
        self._rows = df.to_dict("records")
        self._total_rows = len(self._rows)
        self._dataset_error = None

    def _evaluate_row(self, row: dict[str, Any], step_number: int) -> SimulationEvent:
        """Run the full ML pipeline on one dataset row.

        Must be called under self._lock (to keep step order consistent).
        """
        from ml.assessment import assess_machine  # noqa: PLC0415

        type_ = str(row["Type"]).upper()
        air_temp_k = float(row["Air temperature [K]"])
        process_temp_k = float(row["Process temperature [K]"])
        rpm = float(row["Rotational speed [rpm]"])
        torque = float(row["Torque [Nm]"])
        tool_wear = float(row["Tool wear [min]"])
        product_id = str(row.get("Product ID", ""))

        result = assess_machine(
            air_temp_k=air_temp_k,
            process_temp_k=process_temp_k,
            rotational_speed_rpm=rpm,
            torque_nm=torque,
            tool_wear_min=tool_wear,
            type_=type_,
        )

        return SimulationEvent(
            simulation_step=step_number,
            simulated_time_label=f"Step {step_number}",
            machine_identifier=SIMULATED_MACHINE_ID,
            sensor_values={
                "Air temperature [K]": air_temp_k,
                "Process temperature [K]": process_temp_k,
                "Rotational speed [rpm]": rpm,
                "Torque [Nm]": torque,
                "Tool wear [min]": tool_wear,
                "Type": type_,
                "Product ID": product_id,
            },
            failure_probability=result.failure_probability,
            anomaly_score=result.anomaly_score,
            risk_score=result.risk_score,
            risk_level=result.risk_level,
            is_anomaly=result.is_anomaly,
            predicted_failure=result.predicted_failure,
            failure_threshold=result.failure_threshold,
            model_version=result.model_version,
            real_wall_time=datetime.now(timezone.utc).isoformat(),
        )

    def _generate_alerts(self, event: SimulationEvent) -> None:
        """Generate deterministic informational alerts.

        Must be called under self._lock.
        """
        now = event.real_wall_time
        step = event.simulation_step
        new_alerts: list[SimulationAlert] = []

        # Risk level transition to WARNING or CRITICAL
        if event.risk_level in ("WARNING", "CRITICAL"):
            if event.risk_level != self._previous_risk_level:
                new_alerts.append(SimulationAlert(
                    step=step,
                    alert_type=f"RISK_{event.risk_level}",
                    message=(
                        f"Simulation alert: machine entered {event.risk_level} risk state "
                        f"(risk score {event.risk_score:.3f})."
                    ),
                    risk_level=event.risk_level,
                    real_wall_time=now,
                ))

        # Anomaly transition (False → True)
        if event.is_anomaly and not self._previous_is_anomaly:
            new_alerts.append(SimulationAlert(
                step=step,
                alert_type="ANOMALY",
                message=(
                    f"Simulation alert: anomalous operating pattern detected "
                    f"(anomaly score {event.anomaly_score:.3f})."
                ),
                risk_level=event.risk_level,
                real_wall_time=now,
            ))

        # Failure probability crossed the model threshold
        if event.predicted_failure == 1 and (
            self._current_event is None
            or self._current_event.predicted_failure == 0
        ):
            new_alerts.append(SimulationAlert(
                step=step,
                alert_type="FAILURE_THRESHOLD",
                message=(
                    f"Simulation alert: failure probability "
                    f"({event.failure_probability:.1%}) crossed the model threshold "
                    f"({event.failure_threshold:.3f}). Recommended for review."
                ),
                risk_level=event.risk_level,
                real_wall_time=now,
            ))

        self._alerts.extend(new_alerts)
        if len(self._alerts) > MAX_ALERTS:
            self._alerts = self._alerts[-MAX_ALERTS:]


# ── Module-level singleton ────────────────────────────────────────────────────

#: Shared simulation engine instance (one per process).
_engine = SimulationEngine()


def get_simulation_engine() -> SimulationEngine:
    """Return the module-level singleton simulation engine."""
    return _engine
